### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-html-boilerplate-linting-and-code-style-uRxwab#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://GriffinMartin.github.io/MI-449-SS17-740-html-boilerplate-linting-and-code-style-uRxwab/) and meets the following criteria:

- [x] The files from your last project are copied and pasted into the directory for this project
- [x] Your code returns no errors (warnings are OK) when pasted into the [W3C Validator](https://validator.w3.org/#validate_by_input) (this will also be expected for all future projects)
- [x] Consistent spacing and indentation are used on every line (this will also be expected for all future projects)
- [x] `skeleton.css` is used to improve the design of the page

I think I met you at the Lansing Ruby meet up before. Really excited for this class!

**Comment by chrisvfritz** [comment]
I'm seeing a few issues here:

### Indentation

From the lesson:

> Sibling elements (ones that share the same parent) are always at the same level of indentation

Even though the `h3` and `ul` elements are siblings, the `ul` is still indented beyond the `h3` below:

``` html
<h3>Skills</h3>
	<ul>
		<li>Raindeer trainer</li>
		<li>Supply Chain Management</li>
		<li>Cookie connoisseur</li>
		<li>Sleigh pilot</li>
	</ul>
```

Also, regarding the note:

> just use 2-space indentation

This lesson looks tab-indented instead. See the 3rd page of the lesson under _Settings to better see indentation_ for tips on avoiding this in the future.

### No hosted version

I don't see anything at the hosted link. It looks like the problem is you haven't pushed to the `gh-pages` branch. Don't forget to do this with `git push origin master:gh-pages` whenever you make a change to the site that you'd like published!

---

Can you update the code, then comment on this issue to let me know when it's ready for another look? If you have any questions, also please don't hesitate to ask! 🙂

**Comment by GriffinMartin** [comment]
I fixed it up, thanks for the feedback :)

**Comment by chrisvfritz** [comment]
Magnifique! 🥇 🎉 :shipit:
